"""empty message

Revision ID: 2e17548ddae3
Revises: 41ed9d8793d0
Create Date: 2023-09-22 11:51:58.272264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e17548ddae3'
down_revision: Union[str, None] = '41ed9d8793d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('username', sa.String(), nullable=False))
    op.create_foreign_key(None, 'product', 'user', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'username')
    # ### end Alembic commands ###
